### ISSUE TITLE
Missing build on Windows

### ISSUE THREAD

**Issue by paulbombarde** [benoitc/unicode_util_compat#2]
Hello,

I'm trying to use httpoison on an elixir project (following chapter 13 of the "Programming Elixir" book). Under OSX, everything works fine, but not on windows machines as the unicode_util_compat module is not available.

After digging a little, I see that never unicode_util_compat nor certifi are built on windows. After a quick look, at the doc, adding a win32|win64 pre_hook for both projects made the trick once `make` is available on the target machine.

```
{"(win32|win64)", compile, "make -C uc_spec all"}
```

I hardly know what I'm doing here, but it would be nice if you could add a minimal support for windows.
Best regards,
Paul

**Comment by benoitc** [comment]
I will need to find a windows machine to test. Can you describe your installation?

**Comment by paulbombarde** [comment]
Hello,

The real issue with my solution is that `make` as to be installed on the machine. It is not part of a standard MS/Win build toolchain so people not interrested in cross-platform dev won't have it installed. It is freely available from GnuWin32 or MinGW/MSYS.

I tested this solution on Win7 and WinServer2008 SP2. I will try to test it under Win10, but I'm confindent it will work.

I'll do a little look around the internet to see what's the standard solution for this before making a PR.
Best regards,
Paul

**Comment by josephtazworks** [comment]
I have tested your solution on the latest version of Windows 10.

I have the Ruby DevKit installed on my machine which I believe provides the MinGW set of tools.
I am also using Erlang 19.3 with Elixir 1.4.4.

The provided change above does build and run.

**Comment by benoitc** [comment]
fixed in latest master. This version doesn't require to use Make anymore.

Thanks to @ericmj for the patch!

**Comment by paulbombarde** [comment]
I confirm that the issue is now solved with the latest version. Thanks to all of you !
