### ISSUE TITLE
make build compatible with OTP 21

### ISSUE THREAD

**Issue by benoitc** [benoitc/unicode_util_compat#5]
`string:strip` and some other functions have been removed and prevent the generation of a new module.

**Comment by paulo-ferraz-oliveira** [comment]
Not only is it 21-compatible, but 23-compatible, too.

**Comment by paulo-ferraz-oliveira** [comment]
I had wrongly linked this issue to the PR mentioned in it. I removed the link, but I believe the issue can be safely closed.

**Comment by paulo-ferraz-oliveira** [comment]
Recent changes to this lib. render this Issue obsolete.

**Comment by benoitc** [comment]
true. closing the issue :)
