### ISSUE TITLE
License is either BSD or Apache?

### ISSUE THREAD

**Issue by okeuday** [benoitc/unicode_util_compat#6]
The .app.src file says Apache but the LICENSE file says BSD.  The .app.src file probably wasn't updated?

**Comment by dideler** [comment]
Ran into the same issue.

Note Hex picks up Apache 2.0, but other tools such as [license_finder](https://github.com/pivotal-legacy/LicenseFinder) pick up New BSD (BSD 3-clause).

@benoitc is the project meant to be dual-licensed or is this a discrepancy?

**Comment by benoitc** [comment]
it should have been Apache 2. fixed in current master. Thanks!
