### ISSUE TITLE
add string compat module

### ISSUE THREAD

**Issue by benoitc** [benoitc/unicode_util_compat#7]
like unitcode_compat add the string module for erlang < 20.

**Comment by paulo-ferraz-oliveira** [comment]
I see a `string_compat.erl` inside `src`. This issue is probably dealt with.

**Comment by paulo-ferraz-oliveira** [comment]
I had wrongly linked this issue to the PR mentioned in it. I removed the link, but I believe the issue can be safely closed.

**Comment by paulo-ferraz-oliveira** [comment]
Recent changes to this lib. render this Issue obsolete.

**Comment by benoitc** [comment]
yes. thanks for the head-up!
