### ISSUE TITLE
`string_compat` collides with another library

### ISSUE THREAD

**Issue by g-andrade** [benoitc/unicode_util_compat#9]
The way it's currently named (`string_compat`) makes it collide with an existing [`string_compat`](https://hex.pm/packages/string_compat) library.

Would it be possible to namespace it?

**Comment by benoitc** [comment]
i guess `unicode_string_compat` or `string_util_compat` could do the trick.

**Comment by paulo-ferraz-oliveira** [comment]
Yes, `unicode_string_compat` is a good name (there's a tendency to use the application name as a module name prefix, for several reasons). I'll PR this.

**Comment by paulo-ferraz-oliveira** [comment]
Recent changes to this lib. render this Issue obsolete.

**Comment by benoitc** [comment]
I edited my previous comment, but to make it more clear, the strin_compat application aftr discussing with the author is deprecated in favour of this one since it is supposed to have a short time life (it will be useless once people starts to user Erlang >= 20).
